Allow events to propagate when disabled.
borismus/ray-input pull request #12
Opened 2016-12-08 23:44 UTC by jasonfarrell

Closes #11

2016-12-21 01:56 UTC, borismus requested changes
Sorry, I don't understand what you have in mind with this PR. Have you tested? There seem to be are a bunch of undefined variables, etc.

2016-12-21 01:56 UTC, borismus commented on src/ray-controller.js
> +      if (isMobile() || this.forceVRInteraction) {
Where is this defined?

2016-12-21 01:56 UTC, borismus commented on src/ray-controller.js
> +    if (!this.disabled) {
Why do we need this?

2016-12-21 01:56 UTC, borismus commented on src/ray-controller.js
> +      $(target).parents().each(function(i, el) {
Let's not use $.

2016-12-21 01:56 UTC, borismus commented on src/ray-controller.js
> +    if (!this.disabled) {
Where is this.disabled defined?!

2017-01-05 23:26 UTC, borismus commented
Ping?

2017-01-05 23:28 UTC, jasonfarrell commented
@borismus I'll close this out. I think the problem we were having is we needed an ability to deactivate the library — events wouldn't propagate.

2017-01-05 23:28 UTC, closed without merging